name: gardenctl-updater

on:
  release:
    types:
      - published
    branches:
      - github-action
  # push:
  #   branches:
  #     - github-action
jobs:
  update_gardenctl_in_homebrew_tap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the binary-files
        run: |
          sudo apt-get update
          sudo apt-get install make -y
          make build
          export latest_release_filtered_tag="${GITHUB_REF##*/}"
          echo "the latest release tag is"
          echo $latest_release_filtered_tag
      - name: Upload binaries to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'bin/darwin-amd64/gardenctl-darwin-amd64;bin/linux-amd64/gardenctl-linux-amd64'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: $latest_release_filtered_tag
      - name: Send update with latest versions to gardener/homebrew-tap
        run: |
          mac_sha256sum=$(sha256sum bin/darwin-amd64/gardenctl-darwin-amd64)
          linux_sha256sum=$(sha256sum bin/linux-amd64/gardenctl-linux-amd64)
          echo '{"event_type": "update", "client_payload": { "tag": "'"$latest_release_filtered_tag"'", "mac_sha": "'"$mac_sha256sum"'", "linux_sha": "'"$linux_sha256sum"'"}}'
          curl -X POST https://api.github.com/repos/neo-liang-sap/homebrew-tap/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "update", "client_payload": { "tag": "'"$latest_release_filtered_tag"'", "mac_sha": "'"$mac_sha256sum"'", "linux_sha": "'"$linux_sha256sum"'"}}'